# Generated by Django 2.0.3 on 2018-03-23 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0005_workflow_changes'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionBundle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='workflow',
        ),
        migrations.RemoveField(
            model_name='questiontype',
            name='description',
        ),
        migrations.RemoveField(
            model_name='questiontype',
            name='id',
        ),
        migrations.RemoveField(
            model_name='questiontype',
            name='name',
        ),
        migrations.RemoveField(
            model_name='workflow',
            name='description',
        ),
        migrations.RemoveField(
            model_name='workflow',
            name='id',
        ),
        migrations.RemoveField(
            model_name='workflow',
            name='name',
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bundle_ref', to='workflows.QuestionType'),
        ),
        migrations.AddField(
            model_name='question',
            name='bundle',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='workflows.QuestionBundle'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questiontype',
            name='questionbundle_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='workflows.QuestionBundle'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workflow',
            name='questionbundle_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='workflows.QuestionBundle'),
            preserve_default=False,
        ),
    ]
