# Generated by Django 2.0.3 on 2018-03-26 09:14

from django.db import migrations
from django.db import migrations, models
import django


def copy_data(apps, schema_editor):
    Workflow = apps.get_model('workflows', 'Workflow')
    QuestionBundle = apps.get_model('workflows', 'QuestionBundle')
    QuestionType = apps.get_model('workflows', 'QuestionType')
    Question = apps.get_model('workflows', 'Question')

    print('Move Workflow to bundle')
    for w in Workflow.objects.all():
        print('Create bundle')
        qb = QuestionBundle.objects.create(
            name=w.name,
            description=w.description
        )
        print('Update workflow')
        print('qb.id={}'.format(qb.id))
        w.questionbundle_ptr = qb
        w.save()
        for q in Question.objects.filter(workflow=w.id):
            q.bundle = qb
            q.save()

    print('Move QuestionType to bundle')
    for qt in QuestionType.objects.all():
        print('Create bundle')
        qb = QuestionBundle.objects.create(
            name=qt.name,
            description=qt.description
        )
        qt.questionbundle_ptr = qb
        qt.save()
        for q in Question.objects.filter(question_type=qt.id):
            q.question_type = qb.id
            q.save()


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0006_create_questionbundle'),
    ]

    operations = [
        # migrate data
        migrations.RunPython(copy_data),
    ]
