# Generated by Django 2.0.3 on 2018-03-26 09:14

from django.db import migrations
from django.db import migrations, models
import django


def copy_data(apps, schema_editor):
    Workflow = apps.get_model('workflows', 'Workflow')
    QuestionBundle = apps.get_model('workflows', 'QuestionBundle')
    QuestionType = apps.get_model('workflows', 'QuestionType')
    Question = apps.get_model('workflows', 'Question')

    print('Move Workflow to bundle')
    for w in Workflow.objects.all().order_by('id'):
        qb = QuestionBundle.objects.create(
            name=w.name,
            description=w.description
        )
        print('Create bundle with id={} for workflow.id={}, name={}'.format(qb.id, w.id, w.name))
        w.questionbundle_ptr = qb
        w.save()
        for q in Question.objects.filter(workflow=w.id):
            q.bundle = qb
            q.save()

    print('Move QuestionType to bundle')
    question_type_tmp = {}
    for qt in QuestionType.objects.all():
        qb = QuestionBundle.objects.create(
            name=qt.name,
            description=qt.description
        )
        print('Create bundle with id={} for question_type.id={}, name={}'.format(qb.id, qt.id, qt.name))
        qt.questionbundle_ptr = qb
        qt.save()
        print('After save question_type.id={}'.format(qb.id, qt.id))
        for q in Question.objects.filter(question_type=qt.id):
            question_type_tmp[q.id] = qb.id

    print('Update question_type for question')
    for q in Question.objects.all():
        print('For question={}, old={}, new={}'.format(q.id, q.question_type, question_type_tmp[q.id]))
        q.question_type = question_type_tmp[q.id]
        q.save()


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0006_create_questionbundle'),
    ]

    operations = [
        # migrate data
        migrations.RunPython(copy_data),
    ]
