# Generated by Django 2.0.3 on 2018-03-26 09:28

from django.db import migrations
from django.db import migrations, models
import django


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0007_copy_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='workflow',
        ),

        migrations.RemoveField(
            model_name='questiontype',
            name='description',
        ),

        migrations.RemoveField(
            model_name='questiontype',
            name='id',
        ),

        migrations.RemoveField(
            model_name='workflow',
            name='id',
        ),

        migrations.RemoveField(
            model_name='questiontype',
            name='name',
        ),

        migrations.RemoveField(
            model_name='workflow',
            name='description',
        ),

        migrations.RemoveField(
            model_name='workflow',
            name='name',
        ),
        
        migrations.AlterField(
            model_name='questiontype',
            name='questionbundle_ptr',
            field=models.OneToOneField(auto_created=True, default=None, null=False, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='workflows.QuestionBundle'),
        ),

        migrations.AlterField(
            model_name='workflow',
            name='questionbundle_ptr',
            field=models.OneToOneField(auto_created=True, default=None, null=False, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='workflows.QuestionBundle'),
        ),

        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ref_questions', to='workflows.QuestionType'),
        ),

        # disable null for Question.bundle
        migrations.AlterField(
            model_name='question',
            name='bundle',
            field=models.ForeignKey(default=None, null=False, on_delete=django.db.models.deletion.CASCADE, to='workflows.QuestionBundle'),
        ),


        # autogenerated after all changes

        migrations.AlterField(
            model_name='question',
            name='bundle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflows.QuestionBundle'),
        ),
        migrations.AlterField(
            model_name='questiontype',
            name='questionbundle_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='workflows.QuestionBundle'),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='questionbundle_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='workflows.QuestionBundle'),
        ),

    ]
